language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '10'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
script: ng test --run-in-band=true --ci --bail=1 --pass-with-no-tests --max-workers=2
