language: node_js

node_js: 12

dist: trusty

sudo: required

cache:
  npm: false
  directories:
    - node_modules

install:
  - npm ci

notifications:
  email: true

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script: ng test -i --ci --bail=1 --code-coverage --verbose

after_success:
  - npm run codecov
